# =====================================================
# OpenRCA Project Configuration
# =====================================================

system: "Market"

data_root: "/home/ubuntu/Market"

use_mock: false

default_date: "2021-03-25"

top_k: 1